config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :food_items
    resources :locations
    resources :location_meals
    resources :meals
    resources :serving_times
    resources :users do
      member do
        get :send_user_registration
        get :send_admin_invitation
        get :send_beta_invitation
      end
    end

    root to: "users#index"
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    confirmations: "users/confirmations",
  }

  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?
  post "/graphql", to: "graphql#execute"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # TODO: remove if we ever write any other tests
  get "test_root", to: "rails/welcome#index", as: "test_root_rails"

  # flipper route
  mount Flipper::UI.app(Flipper) => "/flipper"

  resources :recipes, only: [:index]

  resources :multiplier, only: [:index]
  get "/multiplier/*all" => "multiplier#index"

  resources :home, only: [:show] do
    collection do
      get :enable_flip
      get :disable_flip
    end
  end

  authenticated :user do
    get "/preview" => "home#show", id: :preview
    get "/" => redirect("/preview")
  end

  root to: "home#index"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container d-flex justify-content-between">
    <ul class="nav m-3">
      <li class="nav-link">
        © 2021 MealX
      </li>
      <!--
      <li class="nav-link">
        <a href="#">
          Contact Us
        </a>
      </li>
      <li class="nav-link">
        <a href="#">
          About Us
        </a>
      </li>
      <li class="nav-link">
        <a href="#">
          Terms
        </a>
      </li>
      <li class="nav-link">
        <a href="#">
          Privacy
        </a>
      </li>
      <li class="nav-link">
        <a href="#">
          Site Map
        </a>
      </li>
      -->
    </ul>
    <ul class="nav m-3">
      <li class="nav-link text-secondary">
        <i class="fas fa-map-marker-alt"></i>
        Melbourne
      </li>
      <li class="nav-link" target="_blank">
        <a href="https://github.com/failure-driven" alt="Github">
          <i class="fab fa-github"></i>
        </a>
      </li>
      <li class="nav-link" target="_blank">
        <a href="https://failure-driven.com" alt="Failure Driven Blog">
          <i class="fas fa-blog"></i>
        </a>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">MealX</a>

  <div class="collapse navbar-collapse" id="navbarContent">
    <% if signed_in? && current_user && (Flipper[:beta_search].enabled?(current_user) || current_user.user_actions&.dig("admin", "can_administer")) %>
      <ul class="navbar-nav">
        <% if current_user.user_actions&.dig("admin", "can_administer") %>
          <li class="nav-item">
            <%= link_to "Admin", admin_root_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Multiplier", multiplier_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Search", multiplier_index_path + "/search", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Search > Eggs", multiplier_index_path + "/search/eggs", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Search > Duck + chocolate cake", multiplier_index_path + "/search/duck+chocolate+cake", class: "nav-link" %>
        </li>
      </ul>
    <% end %>
  </div>

  <ul class="navbar-nav ml-auto" style="flex-direction: row;">
    <% if signed_in? %>
      <span class="nav-link">
        <%= current_user.email %>
      </span>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
    <% else %>
      <li class="nav-link">
        <%= link_to 'Log in', new_user_session_path, class: "btn" %>
      </li>
      <li class="nav-link">
        <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-primary" %>
      </li>
    <% end %>
  </ul>

  <% if signed_in? && current_user && Flipper[:beta_search].enabled?(current_user) %>
    <button
        class="navbar-toggler"
        style="margin-left: 1em;"
        type="button"
        data-toggle="collapse"
        data-target="#navbarContent"
        aria-controls="navbarToggleContent"
        aria-expanded="false"
        aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mealx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <div class="position-relative">
      <div class="position-absolute col mt-3">
        <div class="container">
          <div class="col">
              <%= flash_messages %>
          </div>
        </div>
      </div>
    </div>
    <div class="pre-container">
      <%= yield :pre_container %>
    </div>
    <main class="container-fluid">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application_devise.html.erb
<% content_for :content do %>
  <div class="row mt-5">
    <div class="col-lg-6 m-auto">
      <div class="card devise-form">
        <div class="card-body devise-form">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render template: "layouts/application" %>